### ISSUE TITLE
Seems to fail parsing ACL's when object groups contain network-object's 

### ISSUE THREAD

**Issue by xandore** [vladimirs-git/cisco-acl#5]
My config contains the following lines:
```
object-group network NETWORK_1
 network-object object ApplicationOut-xx.xxx.xx.xxx
 network-object object XXXXX-network-27
```

When attempting to parse the config I receive the following error:
```
>>> acls = cisco_acl.acls(config=config, platform="ios")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.11/site-packages/cisco_acl/functions.py", line 83, in acls
    _add_addgr_to_aces(acls_, parser)
  File "/root/miniconda3/lib/python3.11/site-packages/cisco_acl/functions.py", line 321, in _add_addgr_to_aces
    addgrs: LAddrGroup = [AddrGroup(**d) for d in parsed_addgrs]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/cisco_acl/functions.py", line 321, in <listcomp>
    addgrs: LAddrGroup = [AddrGroup(**d) for d in parsed_addgrs]
                          ^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/cisco_acl/addr_group.py", line 70, in __init__
    self.items = items
    ^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/cisco_acl/addr_group.py", line 153, in items
    item_: OAddressAg = self._line_to_address(line)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/cisco_acl/addr_group.py", line 389, in _line_to_address
    addr_o = AddressAg(line=line, platform=self._platform, max_ncwb=self.max_ncwb)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/cisco_acl/address_ag.py", line 87, in __init__
    self.line = line
    ^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/cisco_acl/address_ag.py", line 140, in line
    raise ValueError(f"invalid address {line=}")
ValueError: invalid address line='network-object object ApplicationOut-xx.xxx.xx.xxx'
```

It appears as though the code base doesn't have any implementation to parse network-object's when reading in the object-group lines.

**Comment by vladimirs-git** [comment]
'network-object' is not supported. Package designed for Cisco IOS (tested on ISR4331/K9, IOS XE version 16.09.06)
